


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";






CREATE TYPE "public"."genders" AS ENUM (
    'male',
    'female',
    'hidden'
);


ALTER TYPE "public"."genders" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_supervisor_signup"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Debug logging
  RAISE LOG 'Trigger fired: TG_OP=%, role=%, email_confirmed_at=%, id=%', 
    TG_OP, 
    NEW.raw_user_meta_data->>'role', 
    NEW.email_confirmed_at,
    NEW.id;
  
  -- Handle INSERT (user invitation/creation)
  IF TG_OP = 'INSERT' AND NEW.raw_user_meta_data->>'role' = 'supervisor' THEN
    -- Insert into supervisors table with pending status
    INSERT INTO public.supervisors (
      uid,
      first_name,
      last_name,
      email,
      status
    ) VALUES (
      NEW.id,
      NEW.raw_user_meta_data->>'first_name',
      NEW.raw_user_meta_data->>'last_name',
      COALESCE(NEW.raw_user_meta_data->>'email', NEW.email),
      CASE 
        WHEN NEW.email_confirmed_at IS NOT NULL THEN 'active'
        ELSE 'pending'
      END
    )
    ON CONFLICT (uid) DO UPDATE SET
      first_name = EXCLUDED.first_name,
      last_name = EXCLUDED.last_name,
      email = EXCLUDED.email,
      status = EXCLUDED.status;
      
    RAISE LOG 'Supervisor created/updated for user %', NEW.id;
  END IF;
  
  -- Handle UPDATE (email confirmation or other updates)
  IF TG_OP = 'UPDATE' 
     AND NEW.raw_user_meta_data->>'role' = 'supervisor' THEN
    
    -- Update supervisor status based on email confirmation
    UPDATE public.supervisors 
    SET status = CASE 
        WHEN NEW.email_confirmed_at IS NOT NULL THEN 'active'
        ELSE 'pending'
      END,
      email = COALESCE(NEW.raw_user_meta_data->>'email', NEW.email),
      first_name = NEW.raw_user_meta_data->>'first_name',
      last_name = NEW.raw_user_meta_data->>'last_name'
    WHERE uid = NEW.id;
    
    RAISE LOG 'Supervisor status updated for user %', NEW.id;
  END IF;
  
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_supervisor_signup"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."app_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "app_id" bigint,
    "app_name" "text",
    "data" "jsonb"
);


ALTER TABLE "public"."app_logs" OWNER TO "postgres";


ALTER TABLE "public"."app_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."apps" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "data" "jsonb"
);


ALTER TABLE "public"."apps" OWNER TO "postgres";


ALTER TABLE "public"."apps" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."apps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."journals" (
    "id" integer NOT NULL,
    "description" "text",
    "test_user_id" integer,
    "supervisor_uid" "uuid",
    "app_id" bigint,
    "app_name" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."journals" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."journals_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."journals_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."journals_id_seq" OWNED BY "public"."journals"."id";



CREATE TABLE IF NOT EXISTS "public"."supervisors" (
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "uid" "uuid" NOT NULL,
    "status" "text" DEFAULT 'pending'::"text",
    "email" "text",
    CONSTRAINT "supervisors_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'active'::"text"])))
);


ALTER TABLE "public"."supervisors" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."test_users" (
    "id" integer NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "age" integer NOT NULL,
    "gender" "public"."genders" DEFAULT 'male'::"public"."genders" NOT NULL,
    "supervisor_uid" "uuid"
);


ALTER TABLE "public"."test_users" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."test_users_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."test_users_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."test_users_id_seq" OWNED BY "public"."test_users"."id";



ALTER TABLE ONLY "public"."journals" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."journals_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."test_users" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."test_users_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."app_logs"
    ADD CONSTRAINT "app_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."apps"
    ADD CONSTRAINT "apps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."journals"
    ADD CONSTRAINT "journals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."supervisors"
    ADD CONSTRAINT "supervisors_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."test_users"
    ADD CONSTRAINT "test_users_pkey" PRIMARY KEY ("id");



CREATE INDEX "ix_journals_user_id" ON "public"."journals" USING "btree" ("test_user_id");



ALTER TABLE ONLY "public"."app_logs"
    ADD CONSTRAINT "app_logs_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id");



ALTER TABLE ONLY "public"."journals"
    ADD CONSTRAINT "journals_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id");



ALTER TABLE ONLY "public"."journals"
    ADD CONSTRAINT "journals_supervisor_uid_fkey" FOREIGN KEY ("supervisor_uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."journals"
    ADD CONSTRAINT "journals_test_user_id_fkey" FOREIGN KEY ("test_user_id") REFERENCES "public"."test_users"("id");



ALTER TABLE ONLY "public"."supervisors"
    ADD CONSTRAINT "supervisors_uid_fkey" FOREIGN KEY ("uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."test_users"
    ADD CONSTRAINT "test_users_supervisor_uid_fkey" FOREIGN KEY ("supervisor_uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE SET NULL;



CREATE POLICY "all auth users can do all crud operations" ON "public"."apps" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "all auth users can do all crud operations" ON "public"."journals" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "all auth users can do all crud operations" ON "public"."supervisors" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "all auth users can do all crud operations" ON "public"."test_users" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "all auth users can do all crud operations on their own journals" ON "public"."journals" TO "authenticated" USING (("supervisor_uid" = "auth"."uid"())) WITH CHECK (("supervisor_uid" = "auth"."uid"()));



ALTER TABLE "public"."app_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."apps" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "authenticated users can insert app_logs" ON "public"."app_logs" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "authenticated users can read app_logs" ON "public"."app_logs" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."journals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."supervisors" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test_users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





















































































































































































































































































































































































































































































































GRANT ALL ON FUNCTION "public"."handle_supervisor_signup"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_supervisor_signup"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_supervisor_signup"() TO "service_role";






























GRANT ALL ON TABLE "public"."app_logs" TO "anon";
GRANT ALL ON TABLE "public"."app_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."app_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."apps" TO "anon";
GRANT ALL ON TABLE "public"."apps" TO "authenticated";
GRANT ALL ON TABLE "public"."apps" TO "service_role";



GRANT ALL ON SEQUENCE "public"."apps_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."apps_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."apps_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."journals" TO "anon";
GRANT ALL ON TABLE "public"."journals" TO "authenticated";
GRANT ALL ON TABLE "public"."journals" TO "service_role";



GRANT ALL ON SEQUENCE "public"."journals_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."journals_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."journals_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."supervisors" TO "anon";
GRANT ALL ON TABLE "public"."supervisors" TO "authenticated";
GRANT ALL ON TABLE "public"."supervisors" TO "service_role";



GRANT ALL ON TABLE "public"."test_users" TO "anon";
GRANT ALL ON TABLE "public"."test_users" TO "authenticated";
GRANT ALL ON TABLE "public"."test_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_users_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































RESET ALL;
