create table public.app_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  app_id bigint null,
  app_name text null,
  data jsonb null,
  constraint app_logs_pkey primary key (id),
  constraint app_logs_app_id_fkey foreign KEY (app_id) references apps (id)
) TABLESPACE pg_default;

alter table "public"."app_logs" enable row level security;


create policy "all auth users can do all crud operations"
  on "public"."apps"
  as permissive
  for all
  to authenticated
  using (true)
  with check (true);




-- Allow authenticated users to read
create policy "authenticated users can read app_logs"
  on "public"."app_logs"
  as permissive
  for select
  to authenticated
  using (true);

-- Allow authenticated users to insert
create policy "authenticated users can insert app_logs"
  on "public"."app_logs"
  as permissive
  for insert
  to authenticated
  with check (true);
