
  create table "public"."watches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null
      );


alter table "public"."watches" enable row level security;

CREATE UNIQUE INDEX watches_pkey ON public.watches USING btree (id);

alter table "public"."watches" add constraint "watches_pkey" PRIMARY KEY using index "watches_pkey";

alter table "public"."watches" add constraint "watches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."watches" validate constraint "watches_user_id_fkey";

grant delete on table "public"."watches" to "anon";

grant insert on table "public"."watches" to "anon";

grant references on table "public"."watches" to "anon";

grant select on table "public"."watches" to "anon";

grant trigger on table "public"."watches" to "anon";

grant truncate on table "public"."watches" to "anon";

grant update on table "public"."watches" to "anon";

grant delete on table "public"."watches" to "authenticated";

grant insert on table "public"."watches" to "authenticated";

grant references on table "public"."watches" to "authenticated";

grant select on table "public"."watches" to "authenticated";

grant trigger on table "public"."watches" to "authenticated";

grant truncate on table "public"."watches" to "authenticated";

grant update on table "public"."watches" to "authenticated";

grant delete on table "public"."watches" to "postgres";

grant insert on table "public"."watches" to "postgres";

grant references on table "public"."watches" to "postgres";

grant select on table "public"."watches" to "postgres";

grant trigger on table "public"."watches" to "postgres";

grant truncate on table "public"."watches" to "postgres";

grant update on table "public"."watches" to "postgres";

grant delete on table "public"."watches" to "service_role";

grant insert on table "public"."watches" to "service_role";

grant references on table "public"."watches" to "service_role";

grant select on table "public"."watches" to "service_role";

grant trigger on table "public"."watches" to "service_role";

grant truncate on table "public"."watches" to "service_role";

grant update on table "public"."watches" to "service_role";


  create policy "Authenticated can read their own watch"
  on "public"."watches"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Authenticated user can add their own watch"
  on "public"."watches"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



